# Form implementation generated from reading ui file 'cadastro_clientes.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, ct_FormClientes):
        ct_FormClientes.setObjectName("ct_FormClientes")
        ct_FormClientes.resize(700, 500)
        ct_FormClientes.setMinimumSize(QtCore.QSize(700, 500))
        ct_FormClientes.setMaximumSize(QtCore.QSize(700, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icones/adduser_.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ct_FormClientes.setWindowIcon(icon)
        self.fr_FormClientes = QtWidgets.QFrame(ct_FormClientes)
        self.fr_FormClientes.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.fr_FormClientes.setMinimumSize(QtCore.QSize(700, 500))
        self.fr_FormClientes.setMaximumSize(QtCore.QSize(700, 500))
        self.fr_FormClientes.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormClientes.setObjectName("fr_FormClientes")
        self.lb_FormProdutos = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(100, 10, 880, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.tx_Id = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Id.setEnabled(False)
        self.tx_Id.setGeometry(QtCore.QRect(20, 10, 50, 30))
        self.tx_Id.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border: 1px solid #A2A2A2;\n"
"color: #000;\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"}")
        self.tx_Id.setText("")
        self.tx_Id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_Id.setObjectName("tx_Id")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(20, 60, 150, 20))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.tx_Nome = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Nome.setGeometry(QtCore.QRect(20, 90, 401, 25))
        self.tx_Nome.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Nome.setObjectName("tx_Nome")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(20, 200, 630, 30))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(self.fr_FormClientes)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.bt_Salvar = QtWidgets.QPushButton(self.fr_BotoesFormProdutos)
        self.bt_Salvar.setGeometry(QtCore.QRect(520, 0, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_Salvar.setFont(font)
        self.bt_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_Salvar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_Salvar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_Salvar.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_Salvar.setIcon(icon1)
        self.bt_Salvar.setIconSize(QtCore.QSize(50, 25))
        self.bt_Salvar.setObjectName("bt_Salvar")
        self.bt_sair = QtWidgets.QPushButton(self.fr_BotoesFormProdutos)
        self.bt_sair.setGeometry(QtCore.QRect(619, 0, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_sair.setFont(font)
        self.bt_sair.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_sair.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_sair.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_sair.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_sair.setIcon(icon2)
        self.bt_sair.setIconSize(QtCore.QSize(75, 25))
        self.bt_sair.setObjectName("bt_sair")
        self.label_17 = QtWidgets.QLabel(self.fr_BotoesFormProdutos)
        self.label_17.setGeometry(QtCore.QRect(0, 5, 291, 21))
        self.label_17.setStyleSheet("font:10pt \"MS Shell Dlg 2\";")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.lb_FormProdutos_23 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_23.setGeometry(QtCore.QRect(460, 140, 190, 20))
        self.lb_FormProdutos_23.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_23.setObjectName("lb_FormProdutos_23")
        self.lb_FormProdutos_24 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_24.setGeometry(QtCore.QRect(230, 140, 190, 20))
        self.lb_FormProdutos_24.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_24.setObjectName("lb_FormProdutos_24")
        self.tx_Email = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Email.setGeometry(QtCore.QRect(460, 170, 191, 25))
        self.tx_Email.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Email.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Email.setPlaceholderText("")
        self.tx_Email.setObjectName("tx_Email")
        self.tx_Telefone = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Telefone.setGeometry(QtCore.QRect(230, 170, 191, 25))
        self.tx_Telefone.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Telefone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Telefone.setMaxLength(15)
        self.tx_Telefone.setCursorPosition(15)
        self.tx_Telefone.setPlaceholderText("")
        self.tx_Telefone.setObjectName("tx_Telefone")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(20, 240, 131, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.lb_FormProdutos_4 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_4.setGeometry(QtCore.QRect(380, 240, 111, 20))
        self.lb_FormProdutos_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_4.setObjectName("lb_FormProdutos_4")
        self.lb_FormProdutos_15 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_15.setGeometry(QtCore.QRect(20, 320, 120, 20))
        self.lb_FormProdutos_15.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_15.setObjectName("lb_FormProdutos_15")
        self.lb_FormProdutos_6 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_6.setGeometry(QtCore.QRect(380, 320, 121, 20))
        self.lb_FormProdutos_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_6.setObjectName("lb_FormProdutos_6")
        self.tx_Cpf = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Cpf.setGeometry(QtCore.QRect(460, 90, 191, 25))
        self.tx_Cpf.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cpf.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cpf.setMaxLength(14)
        self.tx_Cpf.setCursorPosition(0)
        self.tx_Cpf.setPlaceholderText("")
        self.tx_Cpf.setObjectName("tx_Cpf")
        self.lb_FormProdutos_25 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_25.setGeometry(QtCore.QRect(460, 60, 190, 20))
        self.lb_FormProdutos_25.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_25.setObjectName("lb_FormProdutos_25")
        self.lb_FormProdutos_26 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_26.setGeometry(QtCore.QRect(20, 140, 190, 20))
        self.lb_FormProdutos_26.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_26.setObjectName("lb_FormProdutos_26")
        self.tx_Sus = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Sus.setGeometry(QtCore.QRect(20, 170, 191, 25))
        self.tx_Sus.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Sus.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Sus.setPlaceholderText("")
        self.tx_Sus.setObjectName("tx_Sus")
        self.tx_Ecaminhamento = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Ecaminhamento.setGeometry(QtCore.QRect(20, 270, 281, 25))
        self.tx_Ecaminhamento.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Ecaminhamento.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Ecaminhamento.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Ecaminhamento.setInputMask("")
        self.tx_Ecaminhamento.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Ecaminhamento.setPlaceholderText("")
        self.tx_Ecaminhamento.setObjectName("tx_Ecaminhamento")
        self.tx_Especialidade = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Especialidade.setGeometry(QtCore.QRect(380, 270, 271, 25))
        self.tx_Especialidade.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Especialidade.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Especialidade.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Especialidade.setInputMask("")
        self.tx_Especialidade.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Especialidade.setPlaceholderText("")
        self.tx_Especialidade.setObjectName("tx_Especialidade")
        self.tx_Acompanhante = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Acompanhante.setGeometry(QtCore.QRect(20, 350, 281, 25))
        self.tx_Acompanhante.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Acompanhante.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Acompanhante.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Acompanhante.setInputMask("")
        self.tx_Acompanhante.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Acompanhante.setPlaceholderText("")
        self.tx_Acompanhante.setObjectName("tx_Acompanhante")
        self.tx_Almoco = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Almoco.setGeometry(QtCore.QRect(380, 350, 271, 25))
        self.tx_Almoco.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Almoco.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Almoco.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Almoco.setInputMask("")
        self.tx_Almoco.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Almoco.setPlaceholderText("")
        self.tx_Almoco.setObjectName("tx_Almoco")
        self.lb_FormProdutos_16 = QtWidgets.QLabel(self.fr_FormClientes)
        self.lb_FormProdutos_16.setGeometry(QtCore.QRect(260, 400, 271, 20))
        self.lb_FormProdutos_16.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_16.setObjectName("lb_FormProdutos_16")
        self.tx_Local_atendimento = QtWidgets.QLineEdit(self.fr_FormClientes)
        self.tx_Local_atendimento.setGeometry(QtCore.QRect(20, 430, 631, 25))
        self.tx_Local_atendimento.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Local_atendimento.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Local_atendimento.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Local_atendimento.setInputMask("")
        self.tx_Local_atendimento.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Local_atendimento.setPlaceholderText("")
        self.tx_Local_atendimento.setObjectName("tx_Local_atendimento")

        self.retranslateUi(ct_FormClientes)
        QtCore.QMetaObject.connectSlotsByName(ct_FormClientes)
        ct_FormClientes.setTabOrder(self.tx_Nome, self.tx_Cpf)
        ct_FormClientes.setTabOrder(self.tx_Cpf, self.tx_Sus)
        ct_FormClientes.setTabOrder(self.tx_Sus, self.tx_Telefone)
        ct_FormClientes.setTabOrder(self.tx_Telefone, self.tx_Email)
        ct_FormClientes.setTabOrder(self.tx_Email, self.tx_Ecaminhamento)
        ct_FormClientes.setTabOrder(self.tx_Ecaminhamento, self.tx_Especialidade)
        ct_FormClientes.setTabOrder(self.tx_Especialidade, self.tx_Acompanhante)
        ct_FormClientes.setTabOrder(self.tx_Acompanhante, self.tx_Almoco)
        ct_FormClientes.setTabOrder(self.tx_Almoco, self.tx_Local_atendimento)
        ct_FormClientes.setTabOrder(self.tx_Local_atendimento, self.tx_Id)

    def retranslateUi(self, ct_FormClientes):
        _translate = QtCore.QCoreApplication.translate
        ct_FormClientes.setWindowTitle(_translate("ct_FormClientes", "LC INFORMÁTICA| CADASTRAR"))
        self.lb_FormProdutos.setText(_translate("ct_FormClientes", "FICHA CADASTRAL CLIENTE"))
        self.lb_FormProdutos_2.setText(_translate("ct_FormClientes", "PACIENTE"))
        self.tx_Nome.setPlaceholderText(_translate("ct_FormClientes", "NOME COMPLETO"))
        self.lb_FormProdutos_8.setText(_translate("ct_FormClientes", "INFORMAÇÕES ESSÊNCIAIS"))
        self.bt_Salvar.setText(_translate("ct_FormClientes", "Salvar"))
        self.bt_sair.setText(_translate("ct_FormClientes", "sair"))
        self.label_17.setText(_translate("ct_FormClientes", "Todos os direitos reservados © LC INFORMÁTICA"))
        self.lb_FormProdutos_23.setText(_translate("ct_FormClientes", "EMAIL"))
        self.lb_FormProdutos_24.setText(_translate("ct_FormClientes", "TELEFONE"))
        self.tx_Telefone.setInputMask(_translate("ct_FormClientes", "(00) 0000-00000"))
        self.tx_Telefone.setText(_translate("ct_FormClientes", "() -"))
        self.lb_FormProdutos_3.setText(_translate("ct_FormClientes", "EMCAMINHAMENTO"))
        self.lb_FormProdutos_4.setText(_translate("ct_FormClientes", "ESPECIALIDADE"))
        self.lb_FormProdutos_15.setText(_translate("ct_FormClientes", "ACOMPANHANTE"))
        self.lb_FormProdutos_6.setText(_translate("ct_FormClientes", "ALMOÇO"))
        self.tx_Cpf.setInputMask(_translate("ct_FormClientes", "000.000.000-00"))
        self.tx_Cpf.setText(_translate("ct_FormClientes", "..-"))
        self.lb_FormProdutos_25.setText(_translate("ct_FormClientes", "CPF"))
        self.lb_FormProdutos_26.setText(_translate("ct_FormClientes", "SUS"))
        self.lb_FormProdutos_16.setText(_translate("ct_FormClientes", "LOCAL DE ATENDIMENTO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ct_FormClientes = QtWidgets.QFrame()
    ui = Ui_Cadastro()
    ui.setupUi(ct_FormClientes)
    ct_FormClientes.show()
    sys.exit(app.exec())
